
**Experiment-01**
---



In [17]:
import torch
import numpy as np

###Create 1 D,2D and 3D tensors using Pytorch and Numpy.

In [18]:
np_1d = np.array([1, 2, 3])
pt_1d = torch.tensor([1, 2, 3])

print(f"PyTorch 1D: {pt_1d}")
print(f"NumPy 1D: {np_1d}")

print(f"PyTorch 1D Shape: {pt_1d.shape}")
print(f"NumPy 1D Shape: {np_1d.shape}")

PyTorch 1D: tensor([1, 2, 3])
NumPy 1D: [1 2 3]
PyTorch 1D Shape: torch.Size([3])
NumPy 1D Shape: (3,)


In [19]:
np_2d = np.array([[1, 2, 3], [4, 5, 6]])
pt_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(f"PyTorch 2D: {pt_2d}")
print(f"NumPy 2D: {np_2d}")

print(f"PyTorch 2D Shape: {pt_2d.shape}")
print(f"NumPy 2D Shape: {np_2d.shape}")

PyTorch 2D: tensor([[1, 2, 3],
        [4, 5, 6]])
NumPy 2D: [[1 2 3]
 [4 5 6]]
PyTorch 2D Shape: torch.Size([2, 3])
NumPy 2D Shape: (2, 3)


In [20]:
np_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
pt_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"PyTorch 3D: {pt_3d}")
print(f"NumPy 3D: {np_3d}")

print(f"PyTorch 3D Shape: {pt_3d.shape}")
print(f"NumPy 3D Shape: {np_3d.shape}")

PyTorch 3D: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
NumPy 3D: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
PyTorch 3D Shape: torch.Size([2, 2, 2])
NumPy 3D Shape: (2, 2, 2)


###Show basic operations: Element wise Operations

In [21]:
x = torch.tensor([10, 20, 30])
y = torch.tensor([1, 2, 3])

# Addition
print(x + y)
print(torch.add(x, y))

# Subtraction
print(x - y)
print(torch.sub(x, y))

# Multiplication
print(x * y)

# Division
print(x / y)

tensor([11, 22, 33])
tensor([11, 22, 33])
tensor([ 9, 18, 27])
tensor([ 9, 18, 27])
tensor([10, 40, 90])
tensor([10., 10., 10.])


###Indexing and slicing operations( Boolean Masking, extracting subtensor.. etc)

In [22]:
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(t[0, :])
print(t[:, -1])

# Extract a 2x2 sub-tensor
sub_t = t[:2, :2]
print(sub_t)

tensor([1, 2, 3])
tensor([3, 6, 9])
tensor([[1, 2],
        [4, 5]])


In [23]:
#Boolean masking
data = torch.tensor([10, 25, 3, 45, 2])

mask = data > 20
print(mask)

filtered = data[mask]
print(filtered)

tensor([False,  True, False,  True, False])
tensor([25, 45])


###.view, .reshape .unsqueeze and squeeze function in pytorch

1. **.view():** Returns a new tensor with the same data as the self tensor but different shape. It requires the data to be contiguous in memory. It is faster because it strictly avoids data copying.

2. **.reshape():** Returns a tensor with the same data and number of elements as self but with the specified shape. Unlike .view(), reshape() can handle non-contiguous tensors by creating a copy if necessary. If the tensor is contiguous, it behaves like .view().

3. **.unsqueeze():** Returns a new tensor with a dimension of size one inserted at the specified position (dim). This increases the number of dimensions of the tensor.

4. **squeeze():** Returns a new tensor with all the dimensions of size 1 removed. If a dim argument is provided, only dimensions of size 1 at that specific position are removed.

In [24]:
x = torch.arange(12)

x_view = x.view(3, 4)
x_reshape = x.reshape(3, 4)
print(x_view)
print(x_reshape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [25]:
x = torch.zeros(2, 5) # Shape: (2, 5)

# Unsqueeze: Add a dimension at index 0
x_unsqueezed = x.unsqueeze(0)
print(x_unsqueezed.shape)

# Squeeze: Remove all dimensions of size 1
x_squeezed = x_unsqueezed.squeeze()
print(x_squeezed.shape)

torch.Size([1, 2, 5])
torch.Size([2, 5])


Comparison with NumPy

NumPy uses .reshape() which works similarly to PyTorch's .reshape(). NumPy does not have .view() in the same sense; it relies on .reshape() to handle views vs copies automatically.

###Broadcasting

Broadcasting is the mechanism that allows PyTorch/NumPy to perform operations on tensors of different shapes. The smaller tensor is "broadcast" (stretched) across the larger tensor so they have compatible shapes.

The Rules of Broadcasting:

Align shapes from the last dimension backwards.

Dimensions are compatible if they are equal, or if one of them is 1.

In [26]:
A = torch.tensor([[1],
                  [2],
                  [3]])

B = torch.tensor([4, 5, 6])

# Result: Shape (3, 3)
# A becomes [[1,1,1], [2,2,2], [3,3,3]]
# B becomes [[4,5,6], [4,5,6], [4,5,6]]
C = A + B

print(C)

tensor([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]])


###In-place vs. Out-of-place Operations

**Out-of-place:** Creates a new tensor in memory. The original tensor remains unchanged.

**In-place:** Modifies the data of the original tensor directly. This saves memory but can cause issues with PyTorch's autograd (gradient calculation).

In PyTorch, in-place operations are usually suffixed with an underscore _.

In [27]:
t = torch.tensor([1, 2, 3])

new_t = t.add(10)
print(t)
print(new_t)  #

# In-place
t.add_(10)
print(t)

tensor([1, 2, 3])
tensor([11, 12, 13])
tensor([11, 12, 13])
